FROM ubuntu:16.04

RUN \
apt update -y\
&& apt install -y curl \
&& curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -\
&& apt-get install -y nodejs\
&& apt-get install npm \
&& npm install npm -g \
&& npm install forever -g \
&& npm install cnpm -g \
&& apt install git

RUN cd /root \
&& git clone https://github.com/yutiansut/adminmongo \
&& cd adminmongo && npm install

CMD ["cd /root/adminmongo && npm start"]

